### ISSUE TITLE
[X.x] More info about benefits with Octane

### ISSUE THREAD

**Issue by binaryfire** [Laragear/Preload#12]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [X] I issued a PR with the implementation (optional)

### Description

Hi. Very cool package! But I'm wondering if there will be much of a performance gain if I'm using Octane (since Octane keeps the whole app in memory). Could you provide some clarity on this?

Thanks!

### Code sample

```php
N/A
```

**Comment by DarkGhostHunter** [comment]
> ...there will be much of a performance gain if I'm using Octane?

No. Since PHP scripts are warmed up once each worker lifecycle, and since they last for many requests, the performance gain is negligible. Also, using `opcache.file_cache` and JIT may yield better performance since Opcache will load the file instead of parsing the source code again.

Given how the PHP ecosystem now uses long lifecycles for processes, Preloading seems like a moot point that would only had evident gains the last decade or so. That's until somebody proves me wrong.
